eureka:
  instance:
    hostname: localhost
    homePageUrl: http://localhost:58080/signin_page
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  freemarker:
    template-loader-path: /
    suffix: .ftl
  datasource:
    url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  application:
    name: authorization-service

server:
   port: 58080 # This is the default port anyway, but you can change it here

security:
  jwt:
    token:
      secret-key: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
      
UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data

